# Generated by Django 3.2.7 on 2022-01-30 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamsmodel',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Team'},
        ),
    ]
