# Generated by Django 3.2.7 on 2022-01-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20220131_0243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carsmodel',
            old_name='desription',
            new_name='description',
        ),
        migrations.AddField(
            model_name='carsmodel',
            name='car_photo_5',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='carsmodel',
            name='price',
            field=models.FloatField(),
        ),
    ]
